#cloud-config

package_update: true
package_upgrade: true

runcmd:
  - curl -sL https://deb.nodesource.com/setup_12.x | bash -
  - ["apt-get", "install", "-y", "nodejs"]
  - ["npm", "install", "-g", "forever"]
  - ["iptables", "-A", "INPUT", "-p", "tcp", "--dport", "${port}", "-j", "ACCEPT"]

${yamlencode({
  "ssh_authorized_keys": [for key in authorized_keys : "${key}"],
})}